# Welcome to RiinoSite3!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Riino Site
email: riino@gmail.com
remote_theme: sorphwer/jekyll-theme-panda
description: >- # this means to ignore newlines until "baseurl:",you can add <description>{{ post.content | xml_escape }}</description> in feed.xml.
  A tech blog site of Riisite3.0, from the story of Nest of Etamine Study, owned by Riino.
SEOTitle: RiinoSite Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://riino.site" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sorphwer
github_username:  sorphwer
github_url: https://github.com/sorphwer
repo_url: https://github.com/sorphwer/sorphwer.github.io

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

plugins:
- jekyll-remote-theme
- jekyll-paginate

paginate: 10
gems: ["jemoji"]
toc:
  min_level: 1 # default: 1
  max_level: 4 # default: 6
sass:
    sass_dir: _sass
    style: compressed

navigation:
- text: Home
  url: /index.html
  layout: home
- text: Archive
  url: /archive
  layout: forarchive
# - text: Learn
#   url: /learning.html
  layout: default
- text: profile
  url: /about/
- text : 10-Year Roadmap
  url: /roadmap/

dropdown_header: BLOG #will only exist if dropdown array below has item(s)
dropdown:
- text: Theme
  url : https://riino.site/jekyll-theme-panda/

footer_html: <a href="/terms_of_use">Terms of Use |</a><span></span><a href="/privacy_statement/">Privacy Statement</a>

footer_text:
- Riino Zhang
- Legality and internal compliance review by <a href="https://riino.site/data-collection-policy/"><i>NoEPerspective</i></a>
- Image and animte assets &copy by <a href="https://li.riino.site"><i>Low illuminance</i></a>
- All Rights Reserved.

hoster_logo: /assets/img/logo_Nest.png
hoster_logo_link: https://github.com/sorphwer
hoster_logo_alt: Github
hoster_text:
- Nest of Etamine - 10th Anniversary
- 2012-2022